In [7]:
import pandas as pd

In [11]:
df = pd.read_excel('archive/olympics-data.xlsx').head(11)

In [12]:
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18

In [16]:
dfName = df.name
dfName

0       Jean-François Blanchy
1              Arnaud Boetsch
2                Jean Borotra
3             Jacques Brugnon
4                Albert Canet
5           Nicolas Chatelain
6               Patrick Chila
7                Henri Cochet
8               Marcel Cousin
9          Guy de la Chapelle
10    Élie, Comte de Lastours
Name: name, dtype: object

In [26]:
dfName = df[["name", "born_country", "born_region", "born_city", "born_date"]]

In [28]:
dfName

,name,born_country,born_region,born_city,born_date
0,Jean-François Blanchy,FRA,Gironde,Bordeaux,1886-12-12
1,Arnaud Boetsch,FRA,Yvelines,Meulan,1969-04-01
2,Jean Borotra,FRA,Pyrénées-Atlantiques,Biarritz,1898-08-13
3,Jacques Brugnon,FRA,Paris,Paris VIIIe,1895-05-11
4,Albert Canet,GBR,England,Wandsworth,1878-04-17
5,Nicolas Chatelain,FRA,Somme,Amiens,1970-01-13
6,Patrick Chila,FRA,Essonne,Ris-Orangis,1969-11-27
7,Henri Cochet,FRA,Rhône,Villeurbanne,1901-12-14
8,Marcel Cousin,FRA,Gard,Nîmes,1896-08-04
9,Guy de la Chapelle,FRA,Cher,Farges-Allichamps,1868-07-16
10,"Élie, Comte de Lastours",FRA,Yvelines,Orgeval,1874-08-12

In [27]:
dfName["born_date"] > "1900-01-01"

0     False
1      True
2     False
3     False
4     False
5      True
6      True
7      True
8     False
9     False
10    False
Name: born_date, dtype: bool

In [23]:
dfName[dfName["born_country"].isin("FRA")]

TypeError: only list-like objects are allowed to be passed to isin(), you passed a `str`